<?php

/**
 * Implements hook_context_registry().
 */
function facetapi_context_context_registry() {
  return array(
    'conditions' => array(
      'facetapi_facet_values' => array(
        'title' => t('Facet values'),
        'plugin' => 'facetapi_context_condition_facet_values',
      ),
    ),
  );
}

/**
 * Implements hook_context_plugins().
 */
function facetapi_context_context_plugins() {
  $plugins = array();
  $plugins['facetapi_context_condition_facet_values'] = array(
    'handler' => array(
      'path' => drupal_get_path('module', 'facetapi_context') . '/plugins/context',
      'file' => 'facetapi_context_condition_facet_values.inc',
      'class' => 'facetapi_context_condition_facet_values',
      'parent' => 'context_condition',
    ),
  );
  return $plugins;
}

/**
 * Implements hook_context_page_condition().
 */
function facetapi_context_context_page_condition() {
  if ($plugin = context_get_plugin('condition', 'facetapi_facet_values')) {
    $plugin->execute();
  }
}
