<?php

/**
 * @file
 * Adds questionnaire context, and returns questions, based on taxonomy terms.
 */

/**
 * Implementation of hook_questionnaire_getcontext().
 */
function questionnaire_taxonomy_questionnaire_getcontext($entity_type, $entity, $recipient) {
  $result = array();

  // Entity is a taxonomy term itself. Include this in the context.
  if ($entity_type == 'taxonomy_term') {
    $result['taxonomy_term'][$entity->tid] = $entity;
  }

  // Extract all terms referred to by all taxonomy_term_reference fields.
  $terms = array();
  list($id, $vid, $bundle_name) = entity_extract_ids($entity_type, $entity);
  $fields = field_info_instances($entity_type, $bundle_name);
  foreach ($fields as $field) {
    $field_info = field_info_field($field['field_name']);
    if ($field_info['type'] ==  'taxonomy_term_reference') {
      $field_terms = field_view_field($entity_type, $entity, $field['field_name']);
      $terms = array_merge($terms, $field_terms['#items']);
    }
  }
  foreach($terms as $term) {
    $result['taxonomy_term'][$term['tid']] =  $term['taxonomy_term'];
  }

  return $result;
}

/**
 * Implementation of hook_questionnaire_getquestions().
 */
function questionnaire_taxonomy_questionnaire_getquestions($contexts, $recipient) {
  $questions = array();
  $nodes = array();
  $terms = array();

  if (isset($contexts['taxonomy_term'])) {
    foreach ($contexts['taxonomy_term'] as $term) {
      // load all questions in term
      if ($nids = taxonomy_select_nodes($term->tid, FALSE)) {
        $terms[$term->tid] = $term;
        $nodes[$term->tid] = node_load_multiple($nids, array('type' => 'question'));
      }
    }
  }

  foreach ($nodes as $tid => $node_array) {
    foreach ($node_array as $nodes) {
      $questions[$node->nid] = array(
        'node' => $node,
        'context_type' => 'taxonomy_term',
        'context_id' => $tid,
        'weight' => 0,
      );
    }
  }

  return $questions;
}
